### ISSUE TITLE
Strict time step issue

### ISSUE THREAD

**Issue by imarkonis** [openmeteo/enhydris#20]
Cannot open .hts files in hydrognomon because some time series' time step are defined as strict but they are not [i.e. there are time steps which are not 10min].

**Comment by aptiko** [comment]
This is a hard one. One solution could be for Enhydris to check the time series, like Hydrognomon does. Another would be to fix Hydrognomon so that it can open these time series. We generally need to rethink a bit how these time steps work. I close this ticket, as we only keep tickets that we intend to fix relatively soon.
