### ISSUE TITLE
Internal server error when adding event

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#23]
Run Enhydris locally, go to `http://localhost:8000/`, login, visit a station (e.g. `http://localhost:8000/stations/d/1372/`), select "Add new event"; fill-in date, type and user; leave the report empty. Hit "Submit changes".

Result:

> NoReverseMatch at /gentityevent/add/
> Reverse for 'station_detail' with arguments '()' and keyword arguments '{'object_id': '1372'}' not found. 1 pattern(s) tried: ['stations/d/(?P<pk>\\d+)/$']

**Comment by kickapoo** [comment]
As you see in the latest pull request commit (dd77aa0), solution for this issue is fairly simple. 

Following our coding procedure in order re-generate this error with a UnitTest,

We could check reverse url with:
```python
   resp = self.client.get(reverse('station_detail', kwargs={'object_id': str(gevent.gentity.id)}
```
but the above line as UnitTest for reverse url is totally wrong as in `urls.py` url `station_detail` accepts as  keyword argument `pk` (You stated this in our slack conversion).

Someone could also say, that maybe to check submitting the form with some post data. 
In this case we are dealing with 1 design problem and a redirect catch. 

Check this line, where the actual call from the user is made: https://github.com/openmeteo/enhydris/blob/master/enhydris/hcore/templates/station_detail.html#L96
As you will see, station id is passed as a template variable to `../?station_id={{ station.id }} ` and not something like `/station/<station_id>/gentityevent/add/`. 
As a sequence to the above, if we post valid data to gentityevent form we could could create a UnitTest like this: 
```
    self.assertRedirects(response, expected_url=reverse('gentityevent_add'), status_code=302, target_status_code=200)
```
(https://docs.djangoproject.com/en/1.7/topics/testing/tools/#django.test.SimpleTestCase.assertRedirects)
but this will not re-generate our error and always like be valid as `context['next']='/gentityevent/add/'` is the response  as station_id is not pass to url structure.

So, i will need you help  with UnitTest or you could make an exception to our coding procedure and accept this pull request with a simple reverse TestCase for the new fix.

**Comment by aptiko** [comment]
I didn't know `assertRedirects`, it's quite nice. This is the reason why in many tests you will see that I merely write
```python
self.assertEquals(response.status_code, 302)
```
instead of `assertRedirects`, which does a better job.

Now, I don't fully understand what the problem is. I think the unit test should be quite simple, similar to `GentityFileTestCase` but simpler. Like this:

```python
class GentityEventTestCase(TestCase):

    def setUp(self):
        create_test_data()

    def test_upload_gentity_file(self):
        gentity_id = Station.objects.get(name='Komboti').id

        # Before uploading, there should be 0 events in the database
        self.assertEquals(GentityEvent.objects.filter(gentity__id=gentity_id
                                                      ).count(), 0)

        # Upload an event
        r = self.client.login(username='admin', password='topsecret')
        self.assertTrue(r)
        response = self.client.post(reverse('gentityevent_add'),
                                            {'station_id': gentity_id,
                                             'etc, etc, etc': ...,
                                             })
        self.assertRedirects(response, reverse('gentityevent_add'))

        # Check that the database contains one event
        self.assertEquals(GentityEvent.objects.filter(gentity__i=gentity_id
                                                      ).count(), 1)

        # If you want to do a better job, you can actually check the contents
        # of the record in the database. I don't think that this is absolutely
        # necessary, but it could be a good idea (and it's not hard either).
```
You think that this test would not work properly?

**Comment by kickapoo** [comment]
Unfortunately, I have tried similar approach and test don't work properly (you create test_data much more robust than me).
The `self.assertRedirects(response, reverse('gentityevent_add'))` will pass as valid. Basically `assertRedirect` will search for `reponse.context['next']` which indeed is `/gentityevent_add`.

Maybe I should push my test try? You want to take a look?

**Comment by aptiko** [comment]
Aside from the obvious (code style errors in `test_views.py`, which your checker will find, and the forgotten `ipdb` stuff), there are these issues:

1. Don't create an event type in the unit test, create it in `create_test_data()`. And don't use 'Event Type Description', use something more fancy, such as 'Malfunction' or 'Very important event' or 'End of the world'.
2. Don't retrieve the gentity with name=Komboti. `Station` is a subclass of `Gentity`, so the station with name=Komboti is, let's say, a subobject of the gentity with name=Komboti, and if you have retrieved the first one it has all the properties of the second one. They both have the same id. I also think the form doesn't have a `station_id` field.
3. Since you checked, before posting, that there are 0 events in the database, also check, after you get the redirection, that you have 1 event in the database.
4. You don't need to assign variables `user`, `station` and `event_type`; instead, do it directly like this:

```python
response = self.client.post(
    reverse('gentityevent_add'),
    {'date': '10/06/2015',
     'gentity': Station.objects.get(name='Komboti').id,
     'type': EventType.objects.get(descr='End of the world').id,
     'user': User.objects.get(username='admin').id,
     })
```
