### ISSUE TITLE
Upgrade the CSS framework

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris#309]
Enhydris currently uses Bootstrap 3.

The most obvious choice is to go to Bootstrap 4. It has various advantages:
* I assume it's easier to go from Bootstrap 3 to Bootstrap 4 than it is to go somewhere else (but I don't really know).
* Bootstrap is quite popular, which means many people know it.
* Especially for me, it is important to use something I can use easily. The project doesn't always have good funding, and if next year we have to fix a comma somewhere, I don't want to be stuck because it's using some difficult (for me) technology. I'm familiar with Bootstrap 3 and I expect Bootstrap 4 isn't rocket science.
* Many people think that Bootstrap is a fine framework (of course many also think it sucks :-)

Other options I've thought about:
* BULMA. I've taken a liking for it recently, having been influenced by another colleague, and I created a small project with it.
* Tailwind. It was suggested to me by another colleague.
* No CSS framework. Though I think some people like this solution, I think I'm against it because it would be hard for non-experts to maintain.

@ad0v0 @AbdullahKady opinions?

**Comment by AbdullahKady** [comment]
I thinkk @ad0v0 would have the most concrete opinion, so my opinion should be taken with a grain of salt seeing that I'm not good at UI development.

I personally say we go with bootstrap 4, the main difference between 4&3 is the layout system used (4 uses flexbox instead of floats), which is supposed to be superior! But in general -as far as I have used them-, there isn't much difference/migration-process overhead between the 2 versions.

**Comment by ad0v0** [comment]
@AbdullahKady @aptiko 

I'm actually for sticking to Bootstrap as well. Pros I see:

- Easy in maintenance: lots of people have already used it etc
- Less time speding on migrating proccess rather than switching to another framework 
- Good support and documentation in case if anything goes wrong

Cons: 
- Style overring spendings if there's going to be a need in modifying the existing (in Bootstrap) style for whatever reason
- Extra weight of files due to adding unused JS, which as far as I know can't be removed without having any errorrs with functionality

Personally, I think at this point the pros has a better time&money conversion rate for the client, so I assume that the better decision would be sticking with Bootstrap rather than moving to any other frameworks. Especially, including the fact that we still don't know and haven't agreed on the desired look of the website. But I'm open to discuss other opinions as well.
