### ISSUE TITLE
Django 1.8  upgrade - context_processors 

### ISSUE THREAD

**Issue by kickapoo** [openmeteo/enhydris#48]
Django 1.8 changed context_processor names. 

For instance, `django.core.context_processors.debug` should upgraded to `django.template.context_processors.debug` (Notice,  ...`core`... --> ...`template`...)

**Comment by aptiko** [comment]
This issue does not need a ticket. See the manual, "submitting patches", third bullet. This problem does not need discussion, it is not necessary to fix it at this time, and there is no danger of forgetting it, because Django will start showing warnings about it in version 1.9. (See https://github.com/django/django/blob/stable/1.8.x/django/core/context_processors.py).

It's ok to fix it if you want, and submit a pull request, but it is not necessary. It is routine when upgrading Enhydris to a new Django version to fix all warnings, so it will be done anyway when switching to Django 1.9.
